[pytest]
addopts = --alluredir=allure-results
pythonpath = .
markers =
    login: mark test as part of login tests
    smoke: Smoke tests

[allure]

results_dir = allure-results

# tao directory for allure results
# pytest --alluredir=allure-results

# lay server
# allure serve allure-results    